version: '3'
services:
  imghub:
    restart: always
    ports: # 端口，类似 -p
       - "8081:8081"
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      HubHost: 127.0.0.1
    container_name: imghub

